# Generated by Django 4.0.3 on 2022-03-27 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_desafio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='formato',
        ),
    ]
